### ISSUE TITLE
Menu hidden

### ISSUE THREAD

**Issue by geofranzi** [bexis/Module_FileManagement#26]
![image](https://user-images.githubusercontent.com/15946467/75667187-7dd20180-5c77-11ea-8ad1-36669a23c060.png)

**Comment by EleonoraPetzold** [comment]
was meinst du hier? Das das Menu default eingeklappt sein soll?

**Comment by geofranzi** [comment]
Ist nicht vollständig lesbar, da manchmal länger:
General Informatio ...

müssen das per default breiter machen, oder dynamisch anpassen. So abgehackt ist blöd.

**Comment by EleonoraPetzold** [comment]
oh stimmt, hab ich übersehen...

**Comment by EleonoraPetzold** [comment]
![image](https://user-images.githubusercontent.com/42029171/102222622-f1ca5700-3ee3-11eb-988a-83ce45ee1dab.png)

bei zoom 100% siehts gut aus.  

Wir könnten es so machen wie bei der Suche:
![image](https://user-images.githubusercontent.com/42029171/102222893-51c0fd80-3ee4-11eb-9093-16c9425288b3.png)

Ab einer bestimmten länge wird abgeschnitten.
