### ISSUE TITLE
Add on more section - adapt to B1 changes

### ISSUE THREAD

**Issue by aostrow** [bexis/Module_FileManagement#27]
In B1 one more file upload section came up:
![image](https://user-images.githubusercontent.com/26480843/87790223-8569ff80-c840-11ea-9d0c-96d9abf646e2.png)

Please add to B2.

**Comment by EleonoraPetzold** [comment]
![image](https://user-images.githubusercontent.com/42029171/92595493-bf85d980-f2a4-11ea-8333-9d2e82a532b3.png)
 done
