### ISSUE TITLE
Introduce seperate rights for folders

### ISSUE THREAD

**Issue by aostrow** [bexis/Module_FileManagement#48]
It would be helpful if the access system could distinguish between the folders below a menu entry. Is this possible?

**Comment by aostrow** [comment]
It is configured in Workspace\Modules\FMT\Menu-Config.xml

Idea was:
- every Group entry in the Group-attribute has rights to the folder
- empty children Group-attribute gets rights from parents
- filled children Group-attribute have rights just on this entries (parents must have this entries too or you wont see it)

If I got the idea right, then it seems not to work (or I do wrongly configure it).

PS: before closing it, we need to test it on a deployed version 
- either add a test tag and let the issue open OR
- close it and refer to another test-issue

**Comment by EleonoraPetzold** [comment]
My test on dev:2010 with your config in the menu.xml works. Let's test it together @aostrow

**Comment by aostrow** [comment]
Now It worked also for me. The problem was that it was not deployed on the test server.
